const INCIDENT_TYPES = {
  SOS: "SOS",
  CCTV: "CCTV",
  DISASTER: "DISASTER",
};

const INCIDENT_STATUSES = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  RESOLVED: "RESOLVED",
};

const INCIDENT_SEVERITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

module.exports = {
  INCIDENT_TYPES,
  INCIDENT_STATUSES,
  INCIDENT_SEVERITIES,
};
